"""remove foreign key from payment_key

Revision ID: 1506aeb7009a
Revises: 635b0eb6b625
Create Date: 2025-11-09 02:59:51.871305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1506aeb7009a'
down_revision: Union[str, Sequence[str], None] = '635b0eb6b625'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'cart_histories', ['payment_key'])
    op.drop_constraint(op.f('cart_histories_payment_key_fkey'), 'cart_histories', type_='foreignkey')
    op.create_unique_constraint('uq_payment_payment_key', 'payments', ['payment_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_payment_payment_key', 'payments', type_='unique')
    op.create_foreign_key(op.f('cart_histories_payment_key_fkey'), 'cart_histories', 'payments', ['payment_key'], ['payment_key'])
    op.drop_constraint(None, 'cart_histories', type_='unique')
    # ### end Alembic commands ###
