import type { Metadata } from 'next';
import { Noto_Serif_KR } from 'next/font/google';
import './globals.css';
<<<<<<< HEAD
import ClientWrapper from '@/components/ClientWrapper';
import Providers from './_providers/providers';

const notoSerif = Noto_Serif_KR({
  subsets: ['latin'],
  weight: ['600', '700'],
=======

const notoSerif = Noto_Serif_KR({
  weight: ['400', '700'],
>>>>>>> main
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

<<<<<<< HEAD
export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`${notoSerif.className} min-h-screen px-4 sm:px-8 md:px-12 lg:px-16 xl:px-60 2xl:px-80 bg-[#272625]`}
      >
        <Providers>
          <ClientWrapper>
            <div className="max-w-screen-2xl mx-auto">{children}</div>{' '}
          </ClientWrapper>
        </Providers>
      </body>
=======
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={notoSerif.className}>{children}</body>
>>>>>>> main
    </html>
  );
}
